name: "Slack Notification"
description: "Send Slack notifications for GitHub Actions workflows"

inputs:
  slack_bot_token:
    description: "Slack bot token"
    required: true
  github_user:
    description: "GitHub username to send message to (looked up via email mapping)"
    required: false
  channel_id:
    description: "Slack channel ID (for channel notifications, not user DMs)"
    required: false
    default: "alerts"
  message:
    description: "Message to send to Slack"
    required: true
  blocks:
    description: "Optional Slack blocks for advanced message formatting"
    required: false

runs:
  using: "composite"
  steps:
    - name: Lookup user email
      if: inputs.github_user != ''
      id: lookup_email
      shell: bash
      run: |
        if [[ -z "$USER_MAPPING" ]]; then
          echo "Error: GH_TO_SP_USER_MAPPING environment variable not found"
          exit 1
        fi
        
        EMAIL=$(python3 -c "import json, os; data = json.loads(os.environ['USER_MAPPING']); print(data.get('$GITHUB_USER', ''))")
        
        if [[ -z "$EMAIL" ]]; then
          echo "Error: No email mapping found for GitHub user: $GITHUB_USER"
          exit 1
        fi
        
        echo "email=$EMAIL" >> $GITHUB_OUTPUT
      env:
        GITHUB_USER: ${{ inputs.github_user }}
        USER_MAPPING: ${{ env.GH_TO_SP_USER_MAPPING }}

    - name: Find Slack user by email
      if: inputs.github_user != ''
      id: slack_user
      uses: slackapi/slack-github-action@v2.1
      with:
        method: users.lookupByEmail
        token: ${{ inputs.slack_bot_token }}
        payload: |
          email: ${{ steps.lookup_email.outputs.email }}

    - name: Check Slack lookup success
      if: inputs.github_user != ''
      shell: bash
      run: |
        if [[ "$SLACK_OK" != "true" ]]; then
          echo "Error: Failed to find Slack user for email: $USER_EMAIL"
          exit 1
        fi
      env:
        SLACK_OK: ${{ steps.slack_user.outputs.ok }}
        USER_EMAIL: ${{ steps.lookup_email.outputs.email }}

    - name: Extract Slack user ID
      if: inputs.github_user != ''
      id: user_id
      shell: bash
      run: |
        SLACK_USER_ID=$(python3 -c "import json, os; data = json.loads(os.environ['RESPONSE']); print(data['user']['id'])")
        echo "slack_user_id=$SLACK_USER_ID" >> $GITHUB_OUTPUT
      env:
        RESPONSE: ${{ steps.slack_user.outputs.response }}

    - name: Determine channel
      id: channel
      shell: bash
      run: |
        if [[ -n "$GITHUB_USER_INPUT" ]]; then
          echo "value=$SLACK_USER_ID" >> $GITHUB_OUTPUT
        else
          echo "value=$CHANNEL_ID_INPUT" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_USER_INPUT: ${{ inputs.github_user }}
        CHANNEL_ID_INPUT: ${{ inputs.channel_id }}
        SLACK_USER_ID: ${{ steps.user_id.outputs.slack_user_id }}

    - name: Send Slack notification
      id: send_message
      uses: slackapi/slack-github-action@v2.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          channel: "${{ steps.channel.outputs.value }}"
          text: "${{ inputs.message }}"
          blocks:
          ${{ inputs.blocks }}

    - name: Verify message sent
      if: steps.send_message.outputs.ok == 'false'
      shell: bash
      run: |
        echo "::error::Failed to send Slack message"
        exit 1
