name: "Slack Notification"
description: "Send Slack notifications for GitHub Actions workflows"

inputs:
  slack_bot_token:
    description: "Slack bot token"
    required: true
  github_user:
    description: "GitHub username to send message to (looked up via email mapping)"
    required: false
  channel_id:
    description: "Slack channel ID (for channel notifications, not user DMs)"
    required: false
    default: "alerts"
  message:
    description: "Message to send to Slack"
    required: true
  blocks:
    description: "Optional Slack blocks for advanced message formatting"
    required: false

runs:
  using: "composite"
  steps:
    - name: Load user mapping
      id: user_mapping
      uses: dbeilin-playground/workflows/composite/load-user-mapping@main
      with:
        username: ${{ inputs.github_user }}

    - name: Find Slack user by email
      if: steps.user_mapping.outputs.user_found == 'true'
      id: slack_user
      uses: slackapi/slack-github-action@v2.1
      with:
        method: users.lookupByEmail
        token: ${{ inputs.slack_bot_token }}
        payload: |
          email: ${{ steps.user_mapping.outputs.email }}

    - name: Extract Slack user ID
      if: steps.slack_user.outputs.ok == 'true'
      id: user_id
      shell: bash
      run: |
        SLACK_USER_ID=$(python3 -c "import json, os; data = json.loads(os.environ['RESPONSE']); print(data['user']['id'])")
        echo "slack_user_id=$SLACK_USER_ID" >> $GITHUB_OUTPUT
      env:
        RESPONSE: ${{ steps.slack_user.outputs.response }}

    - name: Determine channel
      id: channel
      shell: bash
      run: |
        # If we have a slack user ID, use it; otherwise fall back to channel
        if [[ -n "$SLACK_USER_ID" ]]; then
          echo "value=$SLACK_USER_ID" >> $GITHUB_OUTPUT
          echo "Sending to user: $SLACK_USER_ID"
        else
          echo "value=$CHANNEL_ID_INPUT" >> $GITHUB_OUTPUT
          echo "Sending to channel: $CHANNEL_ID_INPUT"
        fi
      env:
        CHANNEL_ID_INPUT: ${{ inputs.channel_id }}
        SLACK_USER_ID: ${{ steps.user_id.outputs.slack_user_id }}

    - name: Send Slack notification
      id: send_message
      uses: slackapi/slack-github-action@v2.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          channel: "${{ steps.channel.outputs.value }}"
          text: "${{ inputs.message }}"
          blocks:
          ${{ inputs.blocks }}

    - name: Verify message sent
      if: steps.send_message.outputs.ok == 'false'
      shell: bash
      run: |
        echo "::error::Failed to send Slack message"
        exit 1
