name: "Load User Mapping"
description: "Loads GitHub to Slack email mapping into environment"

runs:
  using: "composite"
  steps:
    - name: Load user mapping to environment
      shell: bash
      run: |
        MAPPING_CONTENT=$(python3 -c "import json; print(json.dumps(json.load(open('${{ github.action_path }}/user-mapping.json'))))")
        echo "GH_TO_SP_USER_MAPPING=$MAPPING_CONTENT" >> $GITHUB_ENV
